### ISSUE TITLE
Type hinty ułatwiłyby pracę nad kodem

### ISSUE THREAD

**Issue by EmilMassey** [Robertkowski/buking#2]
Na przykład tu:

https://github.com/Robertkowski/buking/blob/faa54ddb019ca49f5fbf521919d6fd1a798fa5c1/src/Entity/Reservation.php#L85

**Comment by Robertkowski** [comment]
Poprawione tu:

https://github.com/Robertkowski/buking/blob/f1ff5efa7567b372912a5b295d76bbeedf824353/src/Entity/Reservation.php#L85

jak i w innych miejscach.

**Comment by EmilMassey** [comment]
Fajnie, od razu lepiej się pracuje z kodem. Dzięki za poprawki
