### ISSUE TITLE
Przydałoby się użyć Data Transfer Objects

### ISSUE THREAD

**Issue by EmilMassey** [Robertkowski/buking#3]
W tym momencie type-hinty w encjach sugerują, że ich pola mogą być nullem. Podejrzewam, że to wynika z wygody użycia formularzy w symfony, w których można zmapować formularz do obiektu?
To oczywiście niekoniecznie jest błąd, ale taki kompromis zaciemnia kod i pozwala na tworzenie nieprawidłowych encji.

Przesyłam dwa artykuły w temacie:
https://sarvendev.com/2018/01/encja-byc-zawsze-poprawnym-obiektem/
https://symfonycasts.com/screencast/symfony-forms/form-dto

**Comment by Robertkowski** [comment]
Dodałem Modele:
https://github.com/Robertkowski/buking/tree/master/src/Form/Model

**Comment by EmilMassey** [comment]
Super!
